# Generated by Django 4.1.2 on 2022-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
