# Generated by Django 4.1.2 on 2022-10-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_profile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='pizza_img/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
