# Generated by Django 4.1.2 on 2022-10-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_rename_image_profile_pizza_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pizza_img',
            new_name='get_image',
        ),
    ]
