# Generated by Django 4.1.2 on 2022-10-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_rename_pizza_img_profile_get_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='external_id',
        ),
    ]
