# Generated by Django 4.1.2 on 2022-10-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0010_remove_profile_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='get_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='pizza_img',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
