# Generated by Django 4.1.2 on 2022-10-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0011_remove_profile_get_image_profile_pizza_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pizza_img',
            new_name='img',
        ),
    ]
