# Generated by Django 4.1.2 on 2022-10-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0012_rename_pizza_img_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='get_image',
        ),
    ]
