# Generated by Django 4.1.2 on 2022-10-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0014_remove_profile_get_image_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='get_image',
            field=models.ImageField(default=1, upload_to='pictures/%Y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
