# Generated by Django 4.1.2 on 2022-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0015_remove_profile_image_profile_get_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='get_image',
            field=models.FileField(upload_to='pictures/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
